import pandas as pd
from unittest.mock import patch
from streamlit.testing.v1 import AppTest
from green_rock.entrypoints.streamlit_app import render_badge


# ---------------------------------------------------------------------------
# Unit tests: render_badge HTML output
# ---------------------------------------------------------------------------

def test_render_badge_live_produces_green_html():
    """render_badge must produce green (#388E3C) fixed-position HTML for LIVE status."""
    with patch("green_rock.entrypoints.streamlit_app.st") as mock_st:
        render_badge("LIVE")
        html = mock_st.markdown.call_args[0][0]
        assert "#388E3C" in html, "LIVE badge must use Forest Green"
        assert "LIVE" in html
        assert "position: fixed" in html, "Badge must use fixed positioning"
        assert mock_st.markdown.call_args[1].get("unsafe_allow_html") is True


def test_render_badge_cached_produces_amber_html():
    """render_badge must produce amber (#FBC02D) fixed-position HTML for non-LIVE status."""
    with patch("green_rock.entrypoints.streamlit_app.st") as mock_st:
        render_badge("CACHED")
        html = mock_st.markdown.call_args[0][0]
        assert "#FBC02D" in html, "CACHED badge must use Amber"
        assert "CACHED" in html
        assert "position: fixed" in html, "Badge must use fixed positioning"


# ---------------------------------------------------------------------------
# Integration smoke test: AppTest (uses real pipeline with cached-data fallback)
# ---------------------------------------------------------------------------
# NOTE: AppTest.from_file() executes the script in an isolated context.
# unittest.mock.patch() from the test thread does NOT propagate into that context,
# so we cannot mock DataPipeline here.  The pipeline's live-fetch will time out
# (~1.9 s) and fall back to data/static_snapshot.csv.  The AppTest timeout is
# set to 10 s to accommodate the full fallback path.
# Prerequisite: data/static_snapshot.csv must exist (generated by Story 1.2).

def test_app_renders_narrative_shell_structure():
    """App smoke test: runs against the cached-data fallback, checks Pitch Deck structure."""
    import os
    snapshot_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "data", "static_snapshot.csv"
    )
    if not os.path.exists(os.path.normpath(snapshot_path)):
        import pytest
        pytest.skip("data/static_snapshot.csv not present — run scripts/generate_snapshot.py first")

    at = AppTest.from_file("src/green_rock/entrypoints/streamlit_app.py")
    at.run(timeout=10)

    assert not at.exception, f"App raised an exception: {at.exception}"

    markdowns = [md.value for md in at.markdown]

    # Pitch Deck Scroll: at least two '---' chapter dividers must be present
    divider_count = sum(1 for md in markdowns if md.strip() == "---")
    assert divider_count >= 2, (
        f"Must contain at least 2 '---' chapter dividers, found {divider_count}"
    )

    # Narrative text column must be rendered
    has_narrative = any("Risk Regime Overview" in md for md in markdowns)
    assert has_narrative, "Narrative text section must be rendered"

    # Fixed-position HTML state badge must be in markdown output
    has_badge = any("position: fixed" in md and "DATA:" in md for md in markdowns)
    assert has_badge, "Fixed-position HTML State Badge must be injected into markdown"

    # Title must be present
    titles = [t.value for t in at.title]
    assert any("Green-Rock" in t for t in titles), "Dashboard title must be rendered"
